version: '3'

services:
  web:
    environment:
      - APACHE_RUN_USER=#1000
    build:
      context: ./docker/web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html

  database:
    image: mysql
    restart: always
    ports:
      - 3306:33061
    environment:
      MYSQL_ROOT_PASSWORD: securerootpassword
    volumes:
      - ./docker/database:/var/lib/mysql
