version: '3'

services:
  web:
    environment:
    - APACHE_RUN_USER=#1000
    build:
      context: ./docker/web
    ports:
    - 8010:8100
    volumes:
    - ./:/var/www/html

  database:
    image: mariadb
    restart: always
    ports:
    - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: sighaya123
    volumes:
      - ./docker/database:/var/lib/mysql
