version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: my_laravel_db
      MYSQL_ROOT_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql
  laravel:
    build: .
    volumes:
      - .:/var/www/html
      - laravel-storage:/var/www/html/storage # Persistent storage volume
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
  laravel-storage:
