version: '3'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: sighaya
      DB_USERNAME: sighaya
      DB_PASSWORD: sighaya123

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: sighaya123
      MYSQL_DATABASE: sighaya
      MYSQL_USER: sighaya
      MYSQL_PASSWORD: sighaya123
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
