version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge