version: "3.8"

services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sighaya
      - DB_USERNAME=root
      - DB_PASSWORD=securerootpassword

  nginx:
    build: ./nginx